pipeline {
    agent any
    
    environment{
        EC2_IP = "43.204.231.120"
    }
    stages {
        
        stage('checkout code') {
            steps {
                git branch: 'main',
                credentialsId: 'github-creds',
                url: 'https://github.com/nivedhakiaq/backend-serverdeploy.git'
            }
        }
        
        stage('Deploy to EC2') {
            steps {
                sshagent(['ssh-aws']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} '
                        set -e
                        mkdir -p /home/ubuntu/apps
                        cd /home/ubuntu/apps

                        if [ ! -d backend-project ]; then
                            git clone git@github.com:nivedhakiaq/backend-serverdeploy.git
                        fi

                        
                        cd backend-project
                        git checkout main
                        git pull origin main
                     
                        docker stop myapp || true
                        docker rm myapp || true
                        docker rmi backend-image || true

                        docker build -t backend-image .
                        docker run -d -p 5000:5000 --name myapp backend-image
                    '
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo "✅ DEPLOYMENT SUCCESSFUL"
        }
        failure {
            echo "❌ DEPLOYMENT FAILED"
        }
    }
}
